### ISSUE TITLE
2023-02-23T19:40:29.993Z error: error parse_exception: [parse_exception]

### ISSUE THREAD

**Issue by AndrewGriffinGIT** [koopjs/koop-provider-elasticsearch#60]
Reason: failed to parse [geo_bounding_box] query. [numeric value expected] - ResponseError: parse_exception: [parse_exception] Reason: failed to parse [geo_bounding_box] query. [numeric value expected]
    at onBody (D:\mykoop\node_modules\@koopjs\provider-elasticsearch\node_modules\@elastic\elasticsearch\lib\Transport.js:367:23)
    at IncomingMessage.onEnd (D:\mykoop\node_modules\@koopjs\provider-elasticsearch\node_modules\@elastic\elasticsearch\lib\Transport.js:291:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

 "dependencies": {
    "@koopjs/koop-core": "^8.0.1",
    "@koopjs/provider-elasticsearch": "^3.4.1"
  }

**Comment by rgwozdz** [comment]
@AndrewGriffinGIT - can you give some more context?  I assume this occurs on a particular request.  Can you share?

cc @dhatcher

**Comment by AndrewGriffinGIT** [comment]
@rgwozdz any examples of custom routes writing back to a database through editable feature service?

**Comment by rgwozdz** [comment]
@AndrewGriffinGIT - sorry I don't have any applicable examples.  You define [custom routes on the provider](https://koopjs.github.io/docs/development/provider/routes#provider-specific-routes) and the path would have to be exactly what the client would request for the edit operation and return the expected json success or error message.
